version: "3.8"

services:
  ryvit-docs:
    build: .
    image: ryvit-docs:latest
    restart: unless-stopped
    ports:
      - "120.0.0.1:3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
